### ISSUE TITLE
compatability with remy hatchlings

### ISSUE THREAD

**Issue by joeyjumper94** [Eval427/TDOMI-Remy#1]
Vara does survive if you have the Remy Hatchlings and you selected Vara

`if renpy.python.store_dicts["store"].get("hatchling","Amely")=="Vara":`
is a simple way to check if vara survived thanks to the Remy Hatchlings mod
you can view it here https://github.com/AWSW-Modding/AWSW-Modtools/tree/mod-remy_hatchlings

**Comment by Eval427** [comment]
I'll look into this later. It's going to be a lot of work implementing this since it'll require a ton of extra dialogue, but I can probably make it happen.

**Comment by Eval427** [comment]
Ok most recent content ironically makes this mod completely incompatible with TDOMI.
